name: CI & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install pyinstaller --onefile --collect-all cryptography encryptor.py
      - run: pytest -q || echo "⚠️ No tests yet"

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install pyinstaller
      - run: pyinstaller --onefile encryptor.py
      - uses: actions/upload-artifact@v4
        with:
          name: encryptor-${{ matrix.os }}
          path: dist/*
